import { FormConfig } from '../types/form';

export const coachingForm: FormConfig = {
  id: 'core-energy-coaching-intake',
  title: 'Core Energy Coaching — Leadership Assessment',
  branding: {
    primaryColor: '#1B2A4A',
    primaryContrast: '#ffffff',
    accentColor: '#C8A45E',
    backgroundColor: '#FAFAF8',
    textColor: '#1B2A4A',
    textSecondaryColor: '#5A6A7A',
    fontFamily: "'Inter', sans-serif",
    headingFontFamily: "'Inter', sans-serif",
    borderRadius: 6,
    showPoweredBy: true,
    poweredByText: 'Powered by FormFlow',
    logoPosition: 'top-left',
  },
  settings: {
    progressBar: true,
    keyboardNav: true,
    showQuestionNumbers: true,
    animationDuration: 400,
  },
  questions: [
    {
      id: 'welcome',
      type: 'welcome',
      title: 'Unlock Your Leadership Potential',
      subtitle: 'This brief assessment will help us understand where you are in your leadership journey and how we can best support your growth.',
      description: 'Takes about 3 minutes to complete',
      buttonText: "Let's Begin",
      media: {
        type: 'image',
        url: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=800&q=80',
        alt: 'Team leadership',
        placement: 'background',
        opacity: 0.12,
      },
    },
    {
      id: 'name',
      type: 'short-text',
      title: "First, what's your name?",
      subtitle: "We'd love to know who we're speaking with.",
      placeholder: 'Type your full name...',
      validation: { required: true, minLength: 2 },
    },
    {
      id: 'email',
      type: 'email',
      title: "What's your email address, {{name}}?",
      subtitle: "We'll use this to send you your personalized results.",
      placeholder: 'name@company.com',
      validation: { required: true },
    },
    {
      id: 'role',
      type: 'multiple-choice',
      title: 'What best describes your current role?',
      choices: [
        { id: 'executive', label: 'C-Suite / Executive' },
        { id: 'senior-leader', label: 'Senior Leader / VP / Director' },
        { id: 'mid-manager', label: 'Manager / Team Lead' },
        { id: 'individual', label: 'Individual Contributor' },
        { id: 'entrepreneur', label: 'Entrepreneur / Business Owner' },
        { id: 'transitioning', label: 'Career Transitioning' },
      ],
    },
    {
      id: 'company-size',
      type: 'multiple-choice',
      title: 'How large is your organization?',
      choices: [
        { id: 'solo', label: 'Just me' },
        { id: 'small', label: '2–20 employees' },
        { id: 'medium', label: '21–100 employees' },
        { id: 'large', label: '101–500 employees' },
        { id: 'enterprise', label: '500+ employees' },
      ],
    },
    {
      id: 'biggest-challenge',
      type: 'multiple-choice',
      title: "What's your biggest leadership challenge right now?",
      subtitle: 'Select the one that resonates most.',
      choices: [
        { id: 'team-engagement', label: 'Keeping my team engaged and motivated' },
        { id: 'communication', label: 'Communicating vision and expectations clearly' },
        { id: 'delegation', label: 'Delegating effectively and letting go' },
        { id: 'conflict', label: 'Navigating conflict and difficult conversations' },
        { id: 'burnout', label: 'Managing energy and avoiding burnout' },
        { id: 'growth', label: 'Developing my own leadership skills' },
      ],
    },
    {
      id: 'energy-level',
      type: 'opinion-scale',
      title: 'On a scale of 1-10, how would you rate your current energy level at work?',
      subtitle: 'Where 1 is completely drained and 10 is fully energized.',
      scaleMin: 1,
      scaleMax: 10,
      scaleMinLabel: 'Drained',
      scaleMaxLabel: 'Energized',
    },
    {
      id: 'leadership-rating',
      type: 'rating',
      title: 'How confident do you feel as a leader today?',
      subtitle: 'Be honest — there are no wrong answers.',
      ratingMax: 5,
    },
    {
      id: 'coaching-before',
      type: 'yes-no',
      title: 'Have you worked with a leadership coach before?',
    },
    {
      id: 'goals',
      type: 'long-text',
      title: 'What would success look like for you in the next 6 months?',
      subtitle: 'Paint us a picture of your ideal outcome.',
      placeholder: 'Share your vision...',
      validation: { required: true, minLength: 10 },
    },
    {
      id: 'discovery-call',
      type: 'yes-no',
      title: 'Would you like to schedule a free 30-minute discovery call?',
      subtitle: "No pressure — it's a chance to explore how coaching can help you reach your goals.",
    },
    {
      id: 'end',
      type: 'end',
      title: 'Thank you for sharing!',
      subtitle: "Your responses help us understand your unique leadership journey. We'll be in touch within 24 hours.",
      description: "In the meantime, remember: great leaders aren't born — they're built.",
      media: {
        type: 'image',
        url: 'https://images.unsplash.com/photo-1521791136064-7986c2920216?w=800&q=80',
        alt: 'Handshake',
        placement: 'background',
        opacity: 0.1,
      },
    },
  ],
};
